global:
  namespace: kubeflow
maskrcnn:
  name: maskrcnn-optimized 
  gpus: 8 
  gpus_per_node: 8
  image: # image URL from ECR 
  train_script: /tensorpack-mask-rcnn/MaskRCNN/train.py
  tp_16: 1
  batch_size_per_gpu: 1
  shared_fs: efs 
  data_fs: ebs
  shared_pvc: tensorpack-efs-gp-bursting 
  data_dir: data
  working_dir:  /tensorpack-mask-rcnn
  images_per_epoch: 120000 
  lr_epoch_schedule: "[(8, 0.1), (10, 0.01), (12, None)]"
  eval_period_in_epochs: 24
  data_train: "[\"train2017\"]"
  data_val: "(\"val2017\")" 
  mode_fpn: 'True'
  mode_mask: 'True'
  backbone_norm: FreezeBN
  backbone_weights: data/pretrained-models/ImageNet-R50-AlignPadding.npz
  image_pull_policy: Always 
  horovod_cycle_time: "0.5"
  horovod_fusion_threshold: "67108864"
  nccl_socket_ifname: ^lo,docker0
  nccl_min_rings: 8
  nccl_debug: INFO
