apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeflow-efs-gp-bursting
spec:
  capacity:
    storage: 1Pi 
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - timeo=600
    - noresvport 
  nfs:
    server: <file-system-id>.efs.<region>.amazonaws.com 
    path: "/"
