---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stage-data 
data:
  stage-data.sh: |
    aws s3 cp --recursive s3://$S3_BUCKET/$S3_PREFIX /fsx
---
apiVersion: v1
kind: Pod
metadata:
  name: stage-fsx 
spec:
  restartPolicy: Never
  volumes:
  - name: fsx
    persistentVolumeClaim:
      claimName: # name space persistent volume claim 
  - name: config
    configMap:
      defaultMode: 420
      items:
      - key: stage-data.sh
        mode: 365
        path: stage-data.sh
      name: stage-data 
  containers:
  - name: data
    env:
    - name: S3_BUCKET
      value: my-bucket 
    - name: S3_PREFIX
      value: my-bucket-prefix 
    command:
    -  sh 
    - /etc/config/stage-data.sh
    image: # use image with aws cli support  
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/config
      name: config
    - mountPath: /fsx
      name: fsx
